### ISSUE TITLE
Obrigado por ter postado

### ISSUE THREAD

**Issue by felipexp8** [rafaelloni/Desafio03-GITHUB-Loni#2]
Ficou melhor em ingles, aquela traducao estava estranha

**Comment by rafaelloni** [comment]
Sim, ficou melhor, mas ainda está um pouco confuso.

Pelo que eu entendi, vai custar A para adicionar algo no fim da string (S), e custar B para copiar algo da string e jogar no final. Porém ainda não sei como calculamos o custo disso.
